version: '2'
services:

  web:
    image: takatom/ladder-front:latest
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=ladder.noframeschools.com
      - LETSENCRYPT_HOST=ladder.noframeschools.com
      - LETSENCRYPT_EMAIL=takatomgoo@gmail.com

  api:
    image: takatom/ladder-back:latest
    depends_on:
     - db
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=api.ladder.noframeschools.com
      - LETSENCRYPT_HOST=api.ladder.noframeschools.com
      - LETSENCRYPT_EMAIL=takatomgoo@gmail.com
      - DJANGO_SETTINGS_MODULE=project.settings.production
      - SECRET_KEY
      - DB_USER
      - DB_PASS
      - DB_HOST=db
      - DB_PORT=5432

  db:
    image: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB=ladder

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
